name: 🧪 Comprehensive Testing Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run comprehensive tests daily at 4 AM UTC
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      test-level:
        description: 'Test level to run'
        required: true
        default: 'standard'
        type: choice
        options:
          - standard
          - comprehensive
          - performance
      generate-reports:
        description: 'Generate detailed test reports'
        required: false
        default: true
        type: boolean

env:
  NODE_VERSION: '20'
  FORCE_COLOR: '1'
  CI: 'true'

jobs:
  # ============================================================================
  # THEME STRUCTURE VALIDATION
  # ============================================================================
  theme-structure:
    name: 🏗️ Theme Structure Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
      
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: 📦 Install Dependencies
        run: npm ci
      
      - name: 🏗️ Build Theme
        run: npm run build
      
      - name: 🔍 Validate Theme Structure
        run: |
          echo "🏗️ Running theme structure validation..."
          node scripts/validate-theme-structure.js
          
          echo "📊 Structure validation completed"
      
      - name: 🧪 Run Comprehensive Tests
        if: github.event.inputs.test-level == 'comprehensive' || github.event_name == 'schedule'
        run: |
          echo "🧪 Running comprehensive test suite..."
          npm run test:comprehensive
      
      - name: 📤 Upload Structure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: theme-structure-report
          path: |
            theme.js
            user.css
            manifest.json
            color.ini
          retention-days: 30

  # ============================================================================
  # COLOR SCHEME VALIDATION
  # ============================================================================
  color-validation:
    name: 🌈 Color Scheme Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
      
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: 📦 Install Dependencies
        run: npm ci
      
      - name: 🎨 Build CSS
        run: |
          echo "🎨 Building CSS for color validation..."
          npm run build
          
          # Ensure user.css exists
          if [ ! -f "user.css" ]; then
            echo "❌ user.css not found after build"
            exit 1
          fi
      
      - name: 🌈 Validate Color Schemes
        run: |
          echo "🌈 Running color scheme validation..."
          node scripts/validate-color-schemes.js
          
          echo "📊 Color validation completed"
      
      - name: 🎨 Generate Color Palette Report
        if: github.event.inputs.generate-reports == 'true' || github.event_name == 'schedule'
        run: |
          echo "🎨 Generating color palette report..."
          
          # Create color palette visualization
          cat > color-palette-report.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Catppuccin StarryNight Color Palette</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 20px; }
              .palette { display: flex; flex-wrap: wrap; gap: 10px; margin: 20px 0; }
              .color-item { width: 120px; height: 80px; border-radius: 8px; display: flex; align-items: end; padding: 8px; color: white; font-size: 12px; text-shadow: 1px 1px 2px rgba(0,0,0,0.8); }
              .scheme { margin: 30px 0; }
              h2 { color: #333; border-bottom: 2px solid #ccc; padding-bottom: 5px; }
            </style>
          </head>
          <body>
            <h1>🌌 Catppuccin StarryNight Color Palette</h1>
            <p>Generated on: $(date)</p>
            
            <div class="scheme">
              <h2>Mocha (Dark)</h2>
              <div class="palette">
                <div class="color-item" style="background: #1e1e2e;">base<br>#1e1e2e</div>
                <div class="color-item" style="background: #cdd6f4;">text<br>#cdd6f4</div>
                <div class="color-item" style="background: #89b4fa;">blue<br>#89b4fa</div>
                <div class="color-item" style="background: #b4befe;">lavender<br>#b4befe</div>
                <div class="color-item" style="background: #f5c2e7;">pink<br>#f5c2e7</div>
                <div class="color-item" style="background: #a6e3a1;">green<br>#a6e3a1</div>
                <div class="color-item" style="background: #f9e2af;">yellow<br>#f9e2af</div>
                <div class="color-item" style="background: #fab387;">peach<br>#fab387</div>
              </div>
            </div>
            
            <div class="scheme">
              <h2>Latte (Light)</h2>
              <div class="palette">
                <div class="color-item" style="background: #eff1f5; color: #4c4f69;">base<br>#eff1f5</div>
                <div class="color-item" style="background: #4c4f69;">text<br>#4c4f69</div>
                <div class="color-item" style="background: #1e66f5;">blue<br>#1e66f5</div>
                <div class="color-item" style="background: #7287fd;">lavender<br>#7287fd</div>
                <div class="color-item" style="background: #ea76cb;">pink<br>#ea76cb</div>
                <div class="color-item" style="background: #40a02b;">green<br>#40a02b</div>
                <div class="color-item" style="background: #df8e1d;">yellow<br>#df8e1d</div>
                <div class="color-item" style="background: #fe640b;">peach<br>#fe640b</div>
              </div>
            </div>
            
            <div class="scheme">
              <h2>Accessibility Report</h2>
              <p>All color combinations have been tested for WCAG AA compliance (contrast ratio ≥ 4.5:1)</p>
            </div>
          </body>
          </html>
          EOF
          
          echo "✅ Color palette report generated"
      
      - name: 📤 Upload Color Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: color-validation-report
          path: |
            color-palette-report.html
          retention-days: 30

  # ============================================================================
  # PERFORMANCE REGRESSION TESTING
  # ============================================================================
  performance-regression:
    name: 🚀 Performance Regression Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
      
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: 📦 Install Dependencies
        run: npm ci
      
      - name: 🏗️ Build Theme
        run: npm run build
      
      - name: 🚀 Run Performance Tests
        run: |
          echo "🚀 Running performance regression tests..."
          
          # Bundle size analysis
          js_size=$(wc -c < theme.js)
          css_size=$(wc -c < user.css)
          total_size=$((js_size + css_size))
          
          echo "📊 Bundle Analysis:"
          echo "  JavaScript: $js_size bytes ($(echo \"scale=1; $js_size / 1024\" | bc)KB)"
          echo "  CSS: $css_size bytes ($(echo \"scale=1; $css_size / 1024\" | bc)KB)"
          echo "  Total: $total_size bytes ($(echo \"scale=1; $total_size / 1024\" | bc)KB)"
          
          # Performance budgets (updated for feature-rich theme)
          js_budget=800000    # 800KB
          css_budget=600000   # 600KB
          total_budget=1400000 # 1.4MB
          
          echo "📏 Budget Check:"
          if [ $js_size -gt $js_budget ]; then
            echo "  ❌ JavaScript exceeds budget: $js_size > $js_budget"
            exit 1
          else
            echo "  ✅ JavaScript within budget: $js_size <= $js_budget"
          fi
          
          if [ $css_size -gt $css_budget ]; then
            echo "  ❌ CSS exceeds budget: $css_size > $css_budget"
            exit 1
          else
            echo "  ✅ CSS within budget: $css_size <= $css_budget"
          fi
          
          if [ $total_size -gt $total_budget ]; then
            echo "  ❌ Total exceeds budget: $total_size > $total_budget"
            exit 1
          else
            echo "  ✅ Total within budget: $total_size <= $total_budget"
          fi
          
          echo "🎯 Performance tests passed!"
      
      - name: 🔍 Bundle Analysis
        if: github.event.inputs.test-level == 'performance' || github.event_name == 'schedule'
        run: |
          echo "🔍 Running detailed bundle analysis..."
          
          # Analyze JavaScript bundle
          echo "📊 JavaScript Bundle Analysis:"
          echo "  File size: $(du -h theme.js | cut -f1)"
          echo "  Line count: $(wc -l < theme.js)"
          echo "  Character count: $(wc -c < theme.js)"
          
          # Check for optimization opportunities
          echo "🔍 Optimization Analysis:"
          console_count=$(grep -c "console\." theme.js || echo "0")
          echo "  Console statements: $console_count"
          
          # Check for large functions
          large_functions=$(grep -o "function[^{]*{[^}]\{500,\}" theme.js | wc -l || echo "0")
          echo "  Large functions (>500 chars): $large_functions"
          
          # Compression analysis
          if command -v gzip >/dev/null 2>&1; then
            original_size=$(wc -c < theme.js)
            compressed_size=$(gzip -c theme.js | wc -c)
            compression_ratio=$((compressed_size * 100 / original_size))
            echo "  Compression ratio: ${compression_ratio}%"
          fi
          
          # CSS analysis
          echo "🎨 CSS Bundle Analysis:"
          echo "  File size: $(du -h user.css | cut -f1)"
          echo "  Line count: $(wc -l < user.css)"
          
          # CSS rules analysis
          rule_count=$(grep -c '{' user.css || echo "0")
          echo "  CSS rules: $rule_count"
          
          important_count=$(grep -c '!important' user.css || echo "0")
          echo "  !important declarations: $important_count"
          
          # Check for CSS custom properties
          css_vars=$(grep -c -- '--' user.css || echo "0")
          echo "  CSS custom properties: $css_vars"
      
      - name: 📊 Generate Performance Report
        if: github.event.inputs.generate-reports == 'true' || github.event_name == 'schedule'
        run: |
          echo "📊 Generating performance report..."
          
          cat > performance-report.json << EOF
          {
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "commit": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}",
            "bundles": {
              "javascript": {
                "size": $(wc -c < theme.js),
                "budget": 800000,
                "status": "$([ $(wc -c < theme.js) -le 800000 ] && echo 'pass' || echo 'fail')"
              },
              "css": {
                "size": $(wc -c < user.css),
                "budget": 600000,
                "status": "$([ $(wc -c < user.css) -le 600000 ] && echo 'pass' || echo 'fail')"
              },
              "total": {
                "size": $(($(wc -c < theme.js) + $(wc -c < user.css))),
                "budget": 1400000,
                "status": "$([ $(($(wc -c < theme.js) + $(wc -c < user.css))) -le 1400000 ] && echo 'pass' || echo 'fail')"
              }
            }
          }
          EOF
          
          echo "📊 Performance report generated"
      
      - name: 📤 Upload Performance Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: |
            performance-report.json
          retention-days: 30

  # ============================================================================
  # VISUAL REGRESSION TESTING
  # ============================================================================
  visual-regression:
    name: 👁️ Visual Regression Testing
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event.inputs.test-level == 'comprehensive' || github.event_name == 'schedule'
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
      
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: 📦 Install Dependencies
        run: npm ci
      
      - name: 🏗️ Build Theme
        run: npm run build
      
      - name: 🎨 Generate CSS Screenshots
        run: |
          echo "🎨 Generating CSS visual tests..."
          
          # Create simple HTML file for visual testing
          cat > visual-test.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>StarryNight Visual Test</title>
            <link rel="stylesheet" href="user.css">
            <style>
              body { margin: 0; padding: 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
              .test-container { margin: 20px 0; padding: 20px; border: 1px solid var(--spice-text, #cdd6f4); border-radius: 8px; }
              .color-test { width: 50px; height: 50px; border-radius: 50%; margin: 10px; display: inline-block; }
              .gradient-test { width: 200px; height: 100px; margin: 10px; border-radius: 8px; }
            </style>
          </head>
          <body>
            <h1>🌌 StarryNight Visual Test</h1>
            
            <div class="test-container">
              <h2>Color Variables</h2>
              <div class="color-test" style="background: var(--spice-text, #cdd6f4);"></div>
              <div class="color-test" style="background: var(--spice-base, #1e1e2e);"></div>
              <div class="color-test" style="background: var(--spice-accent, #89b4fa);"></div>
              <div class="color-test" style="background: var(--spice-button, #313244);"></div>
            </div>
            
            <div class="test-container">
              <h2>Gradient Tests</h2>
              <div class="gradient-test" style="background: linear-gradient(45deg, var(--spice-accent, #89b4fa), var(--spice-text, #cdd6f4));"></div>
              <div class="gradient-test" style="background: radial-gradient(circle, var(--spice-button, #313244), var(--spice-base, #1e1e2e));"></div>
            </div>
            
            <div class="test-container">
              <h2>StarryNight Features</h2>
              <div class="gradient-test" style="background: var(--sn-gradient, linear-gradient(45deg, #89b4fa, #b4befe));"></div>
              <div class="gradient-test" style="background: var(--sn-accent, #89b4fa); box-shadow: 0 0 20px var(--sn-glow, rgba(137, 180, 250, 0.3));"></div>
            </div>
          </body>
          </html>
          EOF
          
          echo "✅ Visual test HTML generated"
      
      - name: 📤 Upload Visual Test
        uses: actions/upload-artifact@v4
        with:
          name: visual-regression-test
          path: |
            visual-test.html
            user.css
          retention-days: 30

  # ============================================================================
  # COMPREHENSIVE TEST SUMMARY
  # ============================================================================
  test-summary:
    name: 📋 Test Summary
    runs-on: ubuntu-latest
    needs: [theme-structure, color-validation, performance-regression, visual-regression]
    if: always()
    timeout-minutes: 5
    
    steps:
      - name: 📋 Generate Test Summary
        run: |
          echo "📋 Comprehensive Test Summary"
          echo "============================"
          echo ""
          echo "🏗️ Theme Structure: ${{ needs.theme-structure.result }}"
          echo "🌈 Color Validation: ${{ needs.color-validation.result }}"
          echo "🚀 Performance Regression: ${{ needs.performance-regression.result }}"
          echo "👁️ Visual Regression: ${{ needs.visual-regression.result }}"
          echo ""
          
          # Determine overall status
          if [[ "${{ needs.theme-structure.result }}" == "success" && \
                "${{ needs.color-validation.result }}" == "success" && \
                "${{ needs.performance-regression.result }}" == "success" && \
                ("${{ needs.visual-regression.result }}" == "success" || "${{ needs.visual-regression.result }}" == "skipped") ]]; then
            echo "✅ ALL TESTS PASSED - Theme ready for deployment! 🚀"
            echo "overall-status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Some tests failed - Review required"
            echo "overall-status=failure" >> $GITHUB_OUTPUT
          fi
          
          echo ""
          echo "📊 Test completed for:"
          echo "   Branch: ${{ github.ref_name }}"
          echo "   Commit: ${{ github.sha }}"
          echo "   Event: ${{ github.event_name }}"
          echo "   Test Level: ${{ github.event.inputs.test-level || 'standard' }}"
      
      - name: 📊 Set Status Check
        if: always()
        run: |
          echo "Setting status check for comprehensive tests..."
          if [[ "${{ needs.theme-structure.result }}" == "success" && \
                "${{ needs.color-validation.result }}" == "success" && \
                "${{ needs.performance-regression.result }}" == "success" ]]; then
            echo "✅ Comprehensive tests passed"
          else
            echo "❌ Comprehensive tests failed"
            exit 1
          fi